version: '3.8'
services:
  db:
    image: postgres:15
    container_name: melog-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: katsuhiko
      POSTGRES_PASSWORD: secretpass
      POSTGRES_DB: melog
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
